spring:
  profiles:
    active: prod
    include: common

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jjapflix
    username: root
    password: qwer1234